/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.testfairy.titestfairy;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import com.testfairy.Testfairy;

@Kroll.module(name="Testfairy", id="com.testfairy.titestfairy")
public class TestfairyModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "TestfairyModule";
	private static final boolean DBG = TiConfig.LOGD;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public TestfairyModule()
	{
		super();
	}

	// Methods
	@Kroll.method
	public void begin(String apiKey)
	{
		
	}

	@Kroll.method
	public String version()
	{
		return "version";
	}

	@Kroll.method
	public void pushFeedbackController()
	{
		
	}

	@Kroll.method
	public void sendUserFeedback(String note)
	{
		
	}

	@Kroll.method
	public void updateLocation(String note)
	{
		
	}

	@Kroll.method
	public void checkpoint(String name)
	{
		
	}

	@Kroll.method
	public void setCorrelationId(String name)
	{
		
	}

	@Kroll.method
	public void pause()
	{
		
	}

	@Kroll.method
	public void resume()
	{
		
	}

	@Kroll.method
	public String sessionUrl()
	{
		return "sessionUrl";
	}

	@Kroll.method
	public void takeScreenshot()
	{
		
	}
}

